### PR TITLE
Update MesloLGS NF files

### PR DESCRIPTION
**Pull request by kernelb00t**
This new version of the fonts includes for example an icon for Zorin OS, etc...
(after 3 years, better to be up-to-date !)
The license didn't changed, so not updated. 
If you have any questions, please ask!

### CODE REVIEW

**Comment by kernelb00t** [comment]
These were downloaded from NF official website this morning. I tested them, and installed system wide on Zorin OS 16.2, with GNOME terminal. Everything working fine.

**Comment by kernelb00t** [comment]
I uploaded "Windows compatible Mono" fonts. I have all of the variations, if you need a precise one if there's an issue...

**Comment by kernelb00t** [comment]
Here is the zip file used :
[https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/Meslo.zip](https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/Meslo.zip)

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k/issues/2217. I'll rebuild the font when I get to it.

**Pull request closed without merging**
